### ISSUE TITLE
Using LetsEncrypt module causes 'create' command to fail

### ISSUE THREAD

**Issue by c4ch3c4d3** [qsecure-labs/overlord#9]
**Describe the bug**
When using the LetsEncrypt module, terraform script creation fails

**To Reproduce**
1. usemodule LetsEncrypt
2. set required variables (domain_name)
3. add to campaign
4. create
4. Receive error 'EXCEPTION of type 'UnboundLocalError' occurred with message: 'local variable 'output' referenced before assignment'

**Expected behavior**
File creation as normal.

**Screenshots**
![overlord error](https://user-images.githubusercontent.com/23181631/115620801-df599300-a2b2-11eb-8100-4bd5e4d7bd4c.png)

It seems the debug true variable also no longer exists?

**Desktop (please complete the following information):**
 - OS: Debian 10, totally fresh install

**Comment by Sikkis** [comment]
Thank you for submitting an issue, we will investigate it.

**Comment by Sikkis** [comment]
Hello c4ch3c4d3, I have confirmed the bug. I will investigate the issue further. From a quick look, it seems that the Lets Encrypt module does not correctly handle the name of the redirector module. For now, use the redirectors inside the C2 module until the issue is fixed. 

The 'debug' variable is inherited from the cmd2 package. Its the default throw error message for verbose errors.

**Comment by c4ch3c4d3** [comment]
Sounds good.  I’m still getting a handle on how the C2 default redirector works, I guess there’s no time like the present to figure it out!  Thank you for taking a look!
